# Allen Ben Philipose - 18BIS0043
#### Lab FAT, L53+L54
#### ECE3502 - IoT Domain Analyst
#### Submitted to: Prof. Pradheep T

# Aim

In the given dataset, use random forest and predict the number of cases for 
- 01.03.2021,Belgium (Reg.No: 18BIS0043)

# Algorithm Explanation

Random forests, or random decision forests, are an ensemble learning technique for classification, regression, and other tasks. It works by training a large number of decision trees and then outputing the class that is the mode of the classes (classification) or the mean/average prediction (regression) of the individual trees. Random decision forests compensate for decision trees' inclination for excessive fit to their training set. Although random forests surpass decision trees in practice, their accuracy is lower than that of gradient boosted trees. However, the features of the data might have an effect on their performance.

Each tree in the random forest generates a class prediction, and the class with the most votes becomes the prediction of our model. A large number of substantially uncorrelated models (trees) acting in conjunction outperforms any of the component models individually. A random forest is a meta estimator that fits a number of decision tree classifiers to different subsamples of the dataset and then utilises averaging to increase predicted accuracy and avoid overfitting.

"Random Forest is a classifier that combines many decision trees on diverse subsets of a given dataset and uses the average to increase the dataset's predicted accuracy." Rather of depending on a single decision tree, the random forest collects the forecasts from each tree and forecasts the final output based on the majority vote of forecasts. 

<br />

*Info from documentations*

# Code and Result

## Import Libraries

In [53]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [54]:
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, f1_score 
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import StratifiedKFold, GridSearchCV, KFold 
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report

In [55]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [56]:
import warnings
warnings.filterwarnings('ignore')

In [57]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error
from scipy.stats import spearmanr

## Dataset

In [168]:
allen = pd.read_csv("Dataset.csv")

In [169]:
allen.head()

dateRep  day  month  year  cases  deaths countriesAndTerritories geoId  \
0  14-12-2020   14     12  2020    746       6             Afghanistan    AF   
1  13-12-2020   13     12  2020    298       9             Afghanistan    AF   
2  12-12-2020   12     12  2020    113      11             Afghanistan    AF   
3  11-12-2020   11     12  2020     63      10             Afghanistan    AF   
4  10-12-2020   10     12  2020    202      16             Afghanistan    AF   

  countryterritoryCode  popData2019 continentExp  \
0                  AFG   38041757.0         Asia   
1                  AFG   38041757.0         Asia   
2                  AFG   38041757.0         Asia   
3                  AFG   38041757.0         Asia   
4                  AFG   38041757.0         Asia   

   Cumulative_number_for_14_days_of_COVID-19_cases_per_100000  
0                                           9.013779           
1                                           7.052776           
2                                           6.868768           
3                                           7.134266           
4                                           6.968658

## Pre-processing

In [170]:
allen = allen.drop_duplicates()

In [171]:
allen = allen.dropna()

In [172]:
allen.isnull().sum()

dateRep                                                       0
day                                                           0
month                                                         0
year                                                          0
cases                                                         0
deaths                                                        0
countriesAndTerritories                                       0
geoId                                                         0
countryterritoryCode                                          0
popData2019                                                   0
continentExp                                                  0
Cumulative_number_for_14_days_of_COVID-19_cases_per_100000    0
dtype: int64

In [173]:
allen = allen[allen['continentExp'] == 'Europe']
allen

dateRep  day  month  year  cases  deaths countriesAndTerritories  \
340    14-12-2020   14     12  2020    788      14                 Albania   
341    13-12-2020   13     12  2020    879      12                 Albania   
342    12-12-2020   12     12  2020    802      12                 Albania   
343    11-12-2020   11     12  2020    873      14                 Albania   
344    10-12-2020   10     12  2020    752      15                 Albania   
...           ...  ...    ...   ...    ...     ...                     ...   
58710  17-01-2020   17      1  2020      0       0          United_Kingdom   
58711  16-01-2020   16      1  2020      0       0          United_Kingdom   
58712  15-01-2020   15      1  2020      0       0          United_Kingdom   
58713  14-01-2020   14      1  2020      0       0          United_Kingdom   
58714  13-01-2020   13      1  2020      0       0          United_Kingdom   

      geoId countryterritoryCode  popData2019 continentExp  \
340      AL                  ALB    2862427.0       Europe   
341      AL                  ALB    2862427.0       Europe   
342      AL                  ALB    2862427.0       Europe   
343      AL                  ALB    2862427.0       Europe   
344      AL                  ALB    2862427.0       Europe   
...     ...                  ...          ...          ...   
58710    UK                  GBR   66647112.0       Europe   
58711    UK                  GBR   66647112.0       Europe   
58712    UK                  GBR   66647112.0       Europe   
58713    UK                  GBR   66647112.0       Europe   
58714    UK                  GBR   66647112.0       Europe   

       Cumulative_number_for_14_days_of_COVID-19_cases_per_100000  
340                                           380.970414           
341                                           382.612377           
342                                           370.943958           
343                                           365.459102           
344                                           357.878122           
...                                                  ...           
58710                                           0.000000           
58711                                           0.000000           
58712                                           0.000000           
58713                                           0.000000           
58714                                           0.000000           

[16657 rows x 12 columns]

In [174]:
allen.head()

dateRep  day  month  year  cases  deaths countriesAndTerritories  \
340  14-12-2020   14     12  2020    788      14                 Albania   
341  13-12-2020   13     12  2020    879      12                 Albania   
342  12-12-2020   12     12  2020    802      12                 Albania   
343  11-12-2020   11     12  2020    873      14                 Albania   
344  10-12-2020   10     12  2020    752      15                 Albania   

    geoId countryterritoryCode  popData2019 continentExp  \
340    AL                  ALB    2862427.0       Europe   
341    AL                  ALB    2862427.0       Europe   
342    AL                  ALB    2862427.0       Europe   
343    AL                  ALB    2862427.0       Europe   
344    AL                  ALB    2862427.0       Europe   

     Cumulative_number_for_14_days_of_COVID-19_cases_per_100000  
340                                         380.970414           
341                                         382.612377           
342                                         370.943958           
343                                         365.459102           
344                                         357.878122

In [182]:
allen.drop(allen.columns[0], axis=1, inplace=True)
allen

day  month  year  cases countriesAndTerritories
340     14     12  2020    788                 Albania
341     13     12  2020    879                 Albania
342     12     12  2020    802                 Albania
343     11     12  2020    873                 Albania
344     10     12  2020    752                 Albania
...    ...    ...   ...    ...                     ...
58710   17      1  2020      0          United_Kingdom
58711   16      1  2020      0          United_Kingdom
58712   15      1  2020      0          United_Kingdom
58713   14      1  2020      0          United_Kingdom
58714   13      1  2020      0          United_Kingdom

[16657 rows x 5 columns]

## Train-test-split

In [183]:
allen1 = pd.get_dummies(allen)

In [184]:
allen1.head()

day  month  year  cases  countriesAndTerritories_Albania  \
340   14     12  2020    788                                1   
341   13     12  2020    879                                1   
342   12     12  2020    802                                1   
343   11     12  2020    873                                1   
344   10     12  2020    752                                1   

     countriesAndTerritories_Andorra  countriesAndTerritories_Armenia  \
340                                0                                0   
341                                0                                0   
342                                0                                0   
343                                0                                0   
344                                0                                0   

     countriesAndTerritories_Austria  countriesAndTerritories_Azerbaijan  \
340                                0                                   0   
341                                0                                   0   
342                                0                                   0   
343                                0                                   0   
344                                0                                   0   

     countriesAndTerritories_Belarus  ...  countriesAndTerritories_San_Marino  \
340                                0  ...                                   0   
341                                0  ...                                   0   
342                                0  ...                                   0   
343                                0  ...                                   0   
344                                0  ...                                   0   

     countriesAndTerritories_Serbia  countriesAndTerritories_Slovakia  \
340                               0                                 0   
341                               0                                 0   
342                               0                                 0   
343                               0                                 0   
344                               0                                 0   

     countriesAndTerritories_Slovenia  countriesAndTerritories_Spain  \
340                                 0                              0   
341                                 0                              0   
342                                 0                              0   
343                                 0                              0   
344                                 0                              0   

     countriesAndTerritories_Sweden  countriesAndTerritories_Switzerland  \
340                               0                                    0   
341                               0                                    0   
342                               0                                    0   
343                               0                                    0   
344                               0                                    0   

     countriesAndTerritories_Turkey  countriesAndTerritories_Ukraine  \
340                               0                                0   
341                               0                                0   
342                               0                                0   
343                               0                                0   
344                               0                                0   

     countriesAndTerritories_United_Kingdom  
340                                       0  
341                                       0  
342                                       0  
343                                       0  
344                                       0  

[5 rows x 59 columns]

In [186]:
x = allen1.drop(['cases'],axis=1)

In [187]:
y = allen1['cases']

In [188]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=21)

## Model

In [189]:
data = pd.DataFrame([xtrain.iloc[0]])
for col in data.columns:
    data[col].values[:] = 0

In [190]:
data['countriesAndTerritories_Belgium'] = 1
data['day'] = 1
data['month'] = 3
data['year'] = 2021
xtest = data

## Prediction (18BIS0043)

In [191]:
model1 = RandomForestRegressor(n_estimators=2, random_state=21)
model1.fit(xtrain, ytrain)
p1 = model1.predict(xtest)
print(p1)

[18.5]


In [41]:
model0 = RandomForestRegressor()
model0.fit(xtrain,ytrain)
p0 = model0.predict(xtest)

In [43]:
allen2 = pd.DataFrame(columns=['day','month','year','cases'])

In [48]:
values = {"day": 1, 
          "month": 3,
          "year": 2021,
          "cases": "",
}
allen2 = allen2.append(values, ignore_index=True)

In [49]:
pred = model0.predict(allen2.drop(['cases'],axis=1))
allen2['cases']=pred

In [50]:
allen2.head()

day month  year  cases
0   1     3  2021  31.22
1   1     3  2021  31.22

# Inferences


In [192]:
m = mean_squared_error(ytest,model1.predict(xtest))
print("MSE: %.5f"%m)

ValueError: Found input variables with inconsistent numbers of samples: [3332, 1]

# Viva

Explain the differences between data lake and data warehousing? Which is most suitable for business intelligence applications?

Data warehouse is most suitable for business intelligence application due to the variety of applications that can be made from them due to the large amount of raw data available.

In terms of data storage, the data lake stores all forms of data in their raw form, including structured and unstructured data. It contains data that may be valuable in the present but is also likely to be valuable in the future. Data warehouse only contains high-quality data that has already been pre-processed and is ready for the team to use.
In terms of users, Data lakes are used by data scientists to discover patterns and relevant information that can aid companies, while data warehouses are used by business analysts to develop visualizations and reports.
In terms of purpose, the purpose of Data Lake is not fixed. Sometimes organizations have a future use-case in mind. Its general uses include data discovery, user profiling, and machine learning.
The data warehouse contains data that has been pre-designed for a certain use case. Business Intelligence, Visualizations, and Batch Reporting are just a few of the applications.
In terms of cost, data lakes are comparatively cheaper as data is not necessarily stored in a structured manner. Data warehouses on the other hand are more expensive as well as time consuming.

#### Random Forest

In [97]:
model1 = RandomForestRegressor()
model1.fit(xtrain,ytrain)
p1 = model1.predict(xtest)

In [98]:
print(confusion_matrix(ytest,p1))

[[103   1   2 ...   0   0   0]
 [  8   3   0 ...   0   0   0]
 [  3   5   0 ...   0   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   1   0]]


In [100]:
print(classification_report(ytest.values.ravel(),p1,target_names=list(str(int) for int in range(0,722))))

   0.00         0
         355       0.00      0.00      0.00         0
         356       0.00      0.00      0.00         1
         357       0.00      0.00      0.00         0
         358       0.00      0.00      0.00         0
         359       0.00      0.00      0.00         0
         360       0.00      0.00      0.00         2
         361       0.00      0.00      0.00         1
         362       0.00      0.00      0.00         1
         363       0.00      0.00      0.00         0
         364       0.00      0.00      0.00         1
         365       0.00      0.00      0.00         0
         366       0.00      0.00      0.00         0
         367       0.00      0.00      0.00         1
         368       0.00      0.00      0.00         0
         369       0.00      0.00      0.00         1
         370       0.00      0.00      0.00         1
         371       0.00      0.00      0.00         1
         372       0.00      0.00      0.00         1
         3

#### Decision Tree

In [372]:
model2 = DecisionTreeClassifier()
model2.fit(xtrain,ytrain)
p2 = model2.predict(xtest)

In [373]:
print(confusion_matrix(ytest,p2))

[[1 1 0 0 1 2 0]
 [0 1 0 2 0 0 1]
 [0 1 2 0 0 1 1]
 [1 0 2 5 0 0 0]
 [1 1 1 1 3 0 0]
 [3 1 0 1 0 2 1]
 [0 1 0 0 0 0 1]]


In [374]:
print(classification_report(ytest.values.ravel(),p2,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.17      0.20      0.18         5
           1       0.17      0.25      0.20         4
           2       0.40      0.40      0.40         5
           3       0.56      0.62      0.59         8
           4       0.75      0.43      0.55         7
           5       0.40      0.25      0.31         8
           6       0.25      0.50      0.33         2

    accuracy                           0.38        39
   macro avg       0.38      0.38      0.37        39
weighted avg       0.43      0.38      0.39        39



#### Naive Bayes

In [375]:
model3 = GaussianNB()
model3.fit(xtrain,ytrain)
p3 = model3.predict(xtest)

In [376]:
print(confusion_matrix(ytest,p3))

[[0 3 0 0 2 0 0]
 [1 1 0 2 0 0 0]
 [0 1 4 0 0 0 0]
 [1 2 1 4 0 0 0]
 [1 3 0 0 1 0 2]
 [3 1 0 1 1 2 0]
 [0 1 1 0 0 0 0]]


In [377]:
print(classification_report(ytest.values.ravel(),p3,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.08      0.25      0.12         4
           2       0.67      0.80      0.73         5
           3       0.57      0.50      0.53         8
           4       0.25      0.14      0.18         7
           5       1.00      0.25      0.40         8
           6       0.00      0.00      0.00         2

    accuracy                           0.31        39
   macro avg       0.37      0.28      0.28        39
weighted avg       0.46      0.31      0.33        39



#### K-Nearest Neighbour

In [378]:
model4 = KNeighborsClassifier()
model4.fit(xtrain,ytrain)
p4 = model4.predict(xtest)

In [379]:
print(confusion_matrix(ytest,p4))

[[0 2 0 1 2 0 0]
 [1 1 1 1 0 0 0]
 [0 2 1 1 0 0 1]
 [3 2 1 1 0 0 1]
 [1 2 2 0 1 0 1]
 [4 0 1 0 1 1 1]
 [1 0 0 1 0 0 0]]


In [380]:
print(classification_report(ytest.values.ravel(),p4,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.11      0.25      0.15         4
           2       0.17      0.20      0.18         5
           3       0.20      0.12      0.15         8
           4       0.25      0.14      0.18         7
           5       1.00      0.12      0.22         8
           6       0.00      0.00      0.00         2

    accuracy                           0.13        39
   macro avg       0.25      0.12      0.13        39
weighted avg       0.32      0.13      0.15        39



#### Logistic Regression

In [381]:
model5 = LogisticRegression()
model5.fit(xtrain,ytrain)
p5 = model5.predict(xtest)

In [382]:
print(confusion_matrix(ytest,p5))

[[1 0 0 1 0 0 3]
 [0 0 0 3 0 0 1]
 [0 0 0 5 0 0 0]
 [2 0 0 5 0 0 1]
 [2 0 0 1 0 0 4]
 [2 0 0 4 0 0 2]
 [1 0 0 1 0 0 0]]


In [383]:
print(classification_report(ytest.values.ravel(),p5,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.12      0.20      0.15         5
           1       0.00      0.00      0.00         4
           2       0.00      0.00      0.00         5
           3       0.25      0.62      0.36         8
           4       0.00      0.00      0.00         7
           5       0.00      0.00      0.00         8
           6       0.00      0.00      0.00         2

    accuracy                           0.15        39
   macro avg       0.05      0.12      0.07        39
weighted avg       0.07      0.15      0.09        39

