# Allen Ben Philipose - 18BIS0043
#### Mock Lab FAT, L53+L54
#### ECE3502 - IoT Domain Analyst
#### Submitted to: Prof. Pradheep T

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [33]:
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, f1_score 
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import StratifiedKFold, GridSearchCV, KFold 
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [4]:
import warnings
warnings.filterwarnings('ignore')

## Dataset

In [5]:
allen = pd.read_csv("Dataset.csv")

In [6]:
allen['Online shopping website'] = allen['Online shopping website'].str.upper()

In [7]:
allen.head()

S.No Gender  Age  Amount spend on shopping Online shopping website
0     1      M   18                      1000                  AMAZON
1     2      F   22                      1100                   NYKAA
2     3      F   24                      1150                  MYNTRA
3     4      F   32                      2300                  AMAZON
4     5      F   34                      2200                TATACLIQ

## Label Encoding

#### Gender

In [8]:
l1 = preprocessing.LabelEncoder()
f1 = l1.fit_transform(allen['Gender']) 
f1 = pd.DataFrame(data=f1, columns=['Gender'])
allen['Gender'] = f1['Gender']

In [9]:
print(list(l1.inverse_transform([0,1])))

['F', 'M']


#### Site

In [10]:
l2 = preprocessing.LabelEncoder()
f2 = l2.fit_transform(allen['Online shopping website']) 
f2 = pd.DataFrame(data=f2, columns=['Online shopping website'])
allen['Online shopping website'] = f2['Online shopping website']

In [11]:
print(list(l2.inverse_transform([0,1,2,3,4,5,6])))

['AMAZON', 'BIGBASKET', 'CROMA', 'FLIPKART', 'MYNTRA', 'NYKAA', 'TATACLIQ']


In [12]:
allen.head()

S.No  Gender  Age  Amount spend on shopping  Online shopping website
0     1       1   18                      1000                        0
1     2       0   22                      1100                        5
2     3       0   24                      1150                        4
3     4       0   32                      2300                        0
4     5       0   34                      2200                        6

## Train-test-split

In [13]:
x = allen.drop(['Online shopping website','S.No'],axis=1)

In [14]:
y = allen['Online shopping website']

In [15]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.1,random_state=42)

## Model

In [16]:
model0 = DecisionTreeClassifier()
model0.fit(xtrain,ytrain)
p0 = model0.predict(xtest)

## Prediction (18BIS0043)

In [17]:
allen2 = pd.DataFrame(columns=['Gender','Age','Amount spend on shopping','Online shopping website'])

In [18]:
init = {"Gender": 0, 
        "Age": 34,
        "Amount spend on shopping": 4900,
}
allen2 = allen2.append(init, ignore_index=True)

In [19]:
pred = model0.predict(allen2.drop(['Online shopping website'],axis=1))
allen2['Online shopping website']=pred

In [20]:
allen2.head()

Gender   Age  Amount spend on shopping  Online shopping website
0     0.0  34.0                    4900.0                        5

In [21]:
print(list(l2.inverse_transform([allen2['Online shopping website']])))

['NYKAA']


In [32]:
print(classification_report(ytest.values.ravel(),p0,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.40      0.40      0.40         5
           1       0.67      0.25      0.36         8
           2       0.33      0.50      0.40         6
           3       0.17      0.20      0.18         5
           4       0.33      0.25      0.29         4
           5       0.29      0.40      0.33         5
           6       0.17      0.17      0.17         6

    accuracy                           0.31        39
   macro avg       0.34      0.31      0.30        39
weighted avg       0.36      0.31      0.31        39



## Comparisons

#### Random Forest

In [24]:
model1 = RandomForestClassifier()
model1.fit(xtrain,ytrain)
p1 = model1.predict(xtest)

#### Confusion Matrix 

In [25]:
print(confusion_matrix(ytest,p1))

[[2 0 0 1 0 1 1]
 [0 2 3 2 0 0 1]
 [1 0 3 0 1 1 0]
 [1 0 0 2 1 0 1]
 [1 1 0 0 1 0 1]
 [1 0 2 1 0 1 0]
 [2 0 0 1 0 2 1]]


In [31]:
print(classification_report(ytest.values.ravel(),p1,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.25      0.40      0.31         5
           1       0.67      0.25      0.36         8
           2       0.38      0.50      0.43         6
           3       0.29      0.40      0.33         5
           4       0.33      0.25      0.29         4
           5       0.20      0.20      0.20         5
           6       0.20      0.17      0.18         6

    accuracy                           0.31        39
   macro avg       0.33      0.31      0.30        39
weighted avg       0.35      0.31      0.31        39



#### Decision Tree

In [27]:
model2 = DecisionTreeClassifier()
model2.fit(xtrain,ytrain)
p2 = model2.predict(xtest)

#### Confusion Matrix 

In [28]:
print(confusion_matrix(ytest,p2))

[[2 0 1 1 0 0 1]
 [0 2 3 2 0 0 1]
 [1 0 2 1 1 1 0]
 [1 0 0 1 1 1 1]
 [1 0 0 1 1 0 1]
 [0 0 2 0 0 2 1]
 [2 1 0 1 0 0 2]]


#### Naive Bayes

In [29]:
model3 = GaussianNB()
model3.fit(xtrain,ytrain)
p3 = model3.predict(xtest)

### Confusion Matrix

In [21]:
print(confusion_matrix(ytest,p3))

[[0 1 3 3 3 1 1]
 [0 6 0 2 1 0 1]
 [0 1 2 3 1 0 0]
 [0 2 2 5 0 0 0]
 [0 1 3 1 0 0 1]
 [0 2 1 0 1 3 1]
 [0 3 0 2 0 0 1]]


# K-Nearest Neighbour

In [22]:
model4 = KNeighborsClassifier()
model4.fit(xtrain,ytrain)
p4 = model4.predict(xtest)

### Confusion Matrix

In [23]:
print(confusion_matrix(ytest,p4))

[[5 0 1 3 0 2 1]
 [3 1 0 4 1 1 0]
 [3 0 1 2 0 1 0]
 [3 1 2 2 0 0 1]
 [1 0 2 0 2 0 1]
 [3 0 1 0 1 3 0]
 [3 0 1 0 0 1 1]]


# Logistic Regression

In [24]:
model5 = LogisticRegression()
model5.fit(xtrain,ytrain)
p5 = model5.predict(xtest)

### Confusion Matrix

In [25]:
print(confusion_matrix(ytest,p5))

[[2 0 0 7 0 0 3]
 [2 0 0 7 0 0 1]
 [0 0 0 5 0 0 2]
 [0 0 0 9 0 0 0]
 [0 0 0 4 0 0 2]
 [1 0 0 4 0 0 3]
 [0 0 0 5 0 0 1]]


# K-Fold

In [31]:
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=30)

### Random Forest

In [33]:
acc = np.mean(cross_val_score(model1, xtrain, ytrain, scoring='accuracy', cv=kfold))
pr = np.mean(cross_val_score(model1, xtrain, ytrain, scoring='precision', cv=kfold))
f1s = np.mean(cross_val_score(model1, xtrain, ytrain, scoring='f1', cv=kfold))

ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [174]:
allen1 = pd.DataFrame({'Model':'Random Forest',
                      'Accuracy':[acc],
                      'Precision':[pr],
                      'F1 Score':[f1s]})

### Decision Tree

In [175]:
acc = np.mean(cross_val_score(model2, xtrain, ytrain, scoring='accuracy', cv=kfold))
pr = np.mean(cross_val_score(model2, xtrain, ytrain, scoring='precision', cv=kfold))
f1s = np.mean(cross_val_score(model2, xtrain, ytrain, scoring='f1', cv=kfold))

In [176]:
allen2 = pd.DataFrame({'Model':'Decision Tree',
                      'Accuracy':[acc],
                      'Precision':[pr],
                      'F1 Score':[f1s]})

### Naive Bayes

In [177]:
acc = np.mean(cross_val_score(model3, xtrain, ytrain, scoring='accuracy', cv=kfold))
pr = np.mean(cross_val_score(model3, xtrain, ytrain, scoring='precision', cv=kfold))
f1s = np.mean(cross_val_score(model3, xtrain, ytrain, scoring='f1', cv=kfold))

In [178]:
allen3 = pd.DataFrame({'Model':'Naive Bayes',
                      'Accuracy':[acc],
                      'Precision':[pr],
                      'F1 Score':[f1s]})

### K-Nearest Neighbour

In [179]:
acc = np.mean(cross_val_score(model4, xtrain, ytrain, scoring='accuracy', cv=kfold))
pr = np.mean(cross_val_score(model4, xtrain, ytrain, scoring='precision', cv=kfold))
f1s = np.mean(cross_val_score(model4, xtrain, ytrain, scoring='f1', cv=kfold))

In [180]:
allen4 = pd.DataFrame({'Model':'K-Nearest Neighbour',
                      'Accuracy':[acc],
                      'Precision':[pr],
                      'F1 Score':[f1s]})

### Logistic Regression

In [181]:
acc = np.mean(cross_val_score(model5, xtrain, ytrain, scoring='accuracy', cv=kfold))
# pr = np.mean(cross_val_score(model5, xtrain, ytrain, scoring='precision', cv=kfold))
f1s = np.mean(cross_val_score(model5, xtrain, ytrain, scoring='f1', cv=kfold))

In [182]:
allen5 = pd.DataFrame({'Model':'Logistic Regression',
                      'Accuracy':[acc],
                      'Precision':'NA',
                      'F1 Score':[f1s]})

# Concat

In [183]:
al = pd.concat([allen1,allen2,allen3,allen4,allen5],axis=0).reset_index()
al = al.drop('index',axis=1)
al

Model  Accuracy Precision  F1 Score
0        Random Forest  0.882353  0.812629  0.851371
1        Decision Tree  0.876471  0.850546  0.836372
2          Naive Bayes  0.876471  0.857514  0.816352
3  K-Nearest Neighbour  0.805882  0.798139  0.689109
4  Logistic Regression  0.644118        NA  0.000000