# Allen Ben Philipose - 18BIS0043
#### Mock Lab FAT, L53+L54
#### ECE3502 - IoT Domain Analyst
#### Submitted to: Prof. Pradheep T

# Aim

In the given dataset, use decision tree and predict the online shopping website for 
- F,34,4900 (Reg.No: 18BEC2008-18BIS0057)

# Algorithm Explanation

A decision tree is a flowchart-like framework in which each internal node represents a "test" on an attribute, each branch represents the result of the test, and each leaf node represents a class name (decision taken after computing all attributes). Classification laws are described by the pathways from root to leaf.

A decision tree and its closely associated effect diagram are used in decision research as a visual and empirical decision support method for calculating the predicted values (or expected utility) of competing alternatives.

A decision tree is made up of three distinct forms of nodes:
Nodes of decision – usually denoted by squares
Nodes of chance – usually denoted by circles
End nodes – commonly denoted by triangles


The decision tree is the most effective and widely used classification and prediction method available. A decision tree is a tree structure resembling a flowchart, in which each internal node represents a test on an attribute, each branch represents the test's result, and each leaf node (terminal node) represents a class name.


Decision trees identify instances by sorting them down the tree from the root to a leaf node that corresponds to the instance's classification. As seen in the preceding diagram, an instance is identified by beginning at the root node of the tree, evaluating the attribute defined by this node, and then going down the tree branch corresponding to the value of the attribute. This procedure is then replicated for the new node's subtree.

# Code and Result

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, f1_score 
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import StratifiedKFold, GridSearchCV, KFold 
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [4]:
import warnings
warnings.filterwarnings('ignore')

## Dataset

In [5]:
allen = pd.read_csv("Dataset.csv")

In [6]:
allen['Online shopping website'] = allen['Online shopping website'].str.upper()

In [7]:
allen.head()

S.No Gender  Age  Amount spend on shopping Online shopping website
0     1      M   18                      1000                  AMAZON
1     2      F   22                      1100                   NYKAA
2     3      F   24                      1150                  MYNTRA
3     4      F   32                      2300                  AMAZON
4     5      F   34                      2200                TATACLIQ

## Label Encoding

#### Gender

In [8]:
l1 = preprocessing.LabelEncoder()
f1 = l1.fit_transform(allen['Gender']) 
f1 = pd.DataFrame(data=f1, columns=['Gender'])
allen['Gender'] = f1['Gender']

In [9]:
print(list(l1.inverse_transform([0,1])))

['F', 'M']


#### Site

In [10]:
l2 = preprocessing.LabelEncoder()
f2 = l2.fit_transform(allen['Online shopping website']) 
f2 = pd.DataFrame(data=f2, columns=['Online shopping website'])
allen['Online shopping website'] = f2['Online shopping website']

In [11]:
print(list(l2.inverse_transform([0,1,2,3,4,5,6])))

['AMAZON', 'BIGBASKET', 'CROMA', 'FLIPKART', 'MYNTRA', 'NYKAA', 'TATACLIQ']


In [12]:
allen.head()

S.No  Gender  Age  Amount spend on shopping  Online shopping website
0     1       1   18                      1000                        0
1     2       0   22                      1100                        5
2     3       0   24                      1150                        4
3     4       0   32                      2300                        0
4     5       0   34                      2200                        6

## Train-test-split

In [13]:
x = allen.drop(['Online shopping website','S.No'],axis=1)

In [14]:
y = allen['Online shopping website']

In [15]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.1,random_state=42)

## Model

In [16]:
model0 = DecisionTreeClassifier()
model0.fit(xtrain,ytrain)
p0 = model0.predict(xtest)

## Prediction (18BIS0043)

In [17]:
allen2 = pd.DataFrame(columns=['Gender','Age','Amount spend on shopping','Online shopping website'])

In [18]:
init = {"Gender": 0, 
        "Age": 34,
        "Amount spend on shopping": 4900,
}
allen2 = allen2.append(init, ignore_index=True)

In [19]:
pred = model0.predict(allen2.drop(['Online shopping website'],axis=1))
allen2['Online shopping website']=pred

In [20]:
allen2.head()

Gender   Age  Amount spend on shopping  Online shopping website
0     0.0  34.0                    4900.0                        5

In [21]:
print(list(l2.inverse_transform([allen2['Online shopping website']])))

['NYKAA']


# Inferences

In [22]:
print(classification_report(ytest.values.ravel(),p0,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.67      0.25      0.36         8
           2       0.33      0.50      0.40         6
           3       0.25      0.40      0.31         5
           4       0.33      0.25      0.29         4
           5       0.40      0.40      0.40         5
           6       0.29      0.33      0.31         6

    accuracy                           0.36        39
   macro avg       0.40      0.36      0.36        39
weighted avg       0.41      0.36      0.36        39



# Viva

## Comparisons

#### Random Forest

In [23]:
model1 = RandomForestClassifier()
model1.fit(xtrain,ytrain)
p1 = model1.predict(xtest)

#### Confusion Matrix 

In [24]:
print(confusion_matrix(ytest,p1))

[[2 0 0 1 0 1 1]
 [0 2 3 2 0 0 1]
 [1 0 4 0 1 0 0]
 [1 0 0 2 1 0 1]
 [1 1 0 0 1 0 1]
 [1 0 1 1 0 2 0]
 [2 0 0 1 0 2 1]]


In [25]:
print(classification_report(ytest.values.ravel(),p1,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.25      0.40      0.31         5
           1       0.67      0.25      0.36         8
           2       0.50      0.67      0.57         6
           3       0.29      0.40      0.33         5
           4       0.33      0.25      0.29         4
           5       0.40      0.40      0.40         5
           6       0.20      0.17      0.18         6

    accuracy                           0.36        39
   macro avg       0.38      0.36      0.35        39
weighted avg       0.40      0.36      0.35        39



#### Decision Tree

In [26]:
model2 = DecisionTreeClassifier()
model2.fit(xtrain,ytrain)
p2 = model2.predict(xtest)

#### Confusion Matrix 

In [27]:
print(confusion_matrix(ytest,p2))

[[2 0 0 1 0 1 1]
 [0 2 4 1 0 0 1]
 [0 0 3 2 1 0 0]
 [0 0 0 2 1 1 1]
 [1 0 0 1 1 0 1]
 [0 0 2 0 0 2 1]
 [1 1 0 1 0 2 1]]


In [28]:
print(classification_report(ytest.values.ravel(),p2,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.50      0.40      0.44         5
           1       0.67      0.25      0.36         8
           2       0.33      0.50      0.40         6
           3       0.25      0.40      0.31         5
           4       0.33      0.25      0.29         4
           5       0.33      0.40      0.36         5
           6       0.17      0.17      0.17         6

    accuracy                           0.33        39
   macro avg       0.37      0.34      0.33        39
weighted avg       0.39      0.33      0.33        39



#### Naive Bayes

In [29]:
model3 = GaussianNB()
model3.fit(xtrain,ytrain)
p3 = model3.predict(xtest)

#### Confusion Matrix

In [30]:
print(confusion_matrix(ytest,p3))

[[0 0 1 2 1 1 0]
 [1 3 0 2 1 1 0]
 [0 0 4 0 0 1 1]
 [1 0 0 4 0 0 0]
 [2 0 1 1 0 0 0]
 [1 2 1 0 0 1 0]
 [2 0 1 2 0 0 1]]


In [31]:
print(classification_report(ytest.values.ravel(),p3,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.60      0.38      0.46         8
           2       0.50      0.67      0.57         6
           3       0.36      0.80      0.50         5
           4       0.00      0.00      0.00         4
           5       0.25      0.20      0.22         5
           6       0.50      0.17      0.25         6

    accuracy                           0.33        39
   macro avg       0.32      0.32      0.29        39
weighted avg       0.36      0.33      0.31        39



#### K-Nearest Neighbour

In [32]:
model4 = KNeighborsClassifier()
model4.fit(xtrain,ytrain)
p4 = model4.predict(xtest)

#### Confusion Matrix

In [33]:
print(confusion_matrix(ytest,p4))

[[1 0 1 0 1 0 2]
 [1 2 0 3 1 1 0]
 [1 0 2 0 0 3 0]
 [0 1 0 0 2 1 1]
 [1 0 0 1 1 0 1]
 [1 1 0 0 1 2 0]
 [1 2 0 1 0 0 2]]


In [34]:
print(classification_report(ytest.values.ravel(),p4,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.17      0.20      0.18         5
           1       0.33      0.25      0.29         8
           2       0.67      0.33      0.44         6
           3       0.00      0.00      0.00         5
           4       0.17      0.25      0.20         4
           5       0.29      0.40      0.33         5
           6       0.33      0.33      0.33         6

    accuracy                           0.26        39
   macro avg       0.28      0.25      0.25        39
weighted avg       0.30      0.26      0.26        39



#### Logistic Regression

In [35]:
model5 = LogisticRegression()
model5.fit(xtrain,ytrain)
p5 = model5.predict(xtest)

#### Confusion Matrix

In [36]:
print(confusion_matrix(ytest,p5))

[[0 0 0 5 0 0 0]
 [2 0 0 6 0 0 0]
 [1 0 0 5 0 0 0]
 [1 0 0 4 0 0 0]
 [2 0 0 2 0 0 0]
 [2 0 0 3 0 0 0]
 [2 0 0 4 0 0 0]]


In [37]:
print(classification_report(ytest.values.ravel(),p5,target_names=['0','1','2','3','4','5','6']))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         5
           1       0.00      0.00      0.00         8
           2       0.00      0.00      0.00         6
           3       0.14      0.80      0.24         5
           4       0.00      0.00      0.00         4
           5       0.00      0.00      0.00         5
           6       0.00      0.00      0.00         6

    accuracy                           0.10        39
   macro avg       0.02      0.11      0.03        39
weighted avg       0.02      0.10      0.03        39



## K-Fold

In [38]:
kfold = StratifiedKFold(n_splits=5, shuffle=True, random_state=30)

#### Random Forest

In [39]:
acc = np.mean(cross_val_score(model1, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [40]:
allen11 = pd.DataFrame({'Model':'Random Forest',
                      'Accuracy':[acc]})

#### Decision Tree

In [41]:
acc = np.mean(cross_val_score(model2, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [42]:
allen12 = pd.DataFrame({'Model':'Decision Tree',
                      'Accuracy':[acc]})

#### Naive Bayes

In [43]:
acc = np.mean(cross_val_score(model3, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [44]:
allen13 = pd.DataFrame({'Model':'Naive Bayes',
                      'Accuracy':[acc]})

#### K-Nearest Neighbour

In [45]:
acc = np.mean(cross_val_score(model4, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [46]:
allen14 = pd.DataFrame({'Model':'K-Nearest Neighbour',
                      'Accuracy':[acc]})

#### Logistic Regression

In [47]:
acc = np.mean(cross_val_score(model5, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [48]:
allen15 = pd.DataFrame({'Model':'Logistic Regression',
                      'Accuracy':[acc]})

#### Concat

In [50]:
al = pd.concat([allen11,allen12,allen13,allen14,allen15],axis=0).reset_index()
al = al.drop('index',axis=1)
al

Model  Accuracy
0        Random Forest  0.262733
1        Decision Tree  0.285921
2          Naive Bayes  0.236687
3  K-Nearest Neighbour  0.211097
4  Logistic Regression  0.190766