# Import Libraries

In [20]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import MinMaxScaler

# Dataset

In [21]:
allen = pd.read_csv("Dataset.csv")

In [29]:
allen.head()

Mat  Inn  NO   Runs   HS    Avg  100  50   0
0  200  329  33  15921  248  53.78   51  68  14
1  168  287  29  13378  257  51.85   41  62  17
2  166  280  40  13289  224  55.37   45  58  16
3  164  286  32  13288  270  52.31   36  63   8
4  161  291  16  12472  294  45.35   33  57   9

# Training

In [23]:
allen = allen.drop(['Player','Span'],axis=1)

In [30]:
x = allen.drop(['HS'],axis=1)

In [31]:
y = allen['HS']

In [33]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=1)

In [37]:
model = RandomForestClassifier()
model.fit(xtrain,ytrain)
p = model.predict(xtest)
p

array([194, 217, 129, 137, 174, 205, 159, 121, 154, 216, 154, 242,  51,
       110, 125, 169, 336, 137, 184, 100, 206, 261, 259, 158, 174, 134,
       250, 117, 224, 335, 228, 157, 128, 206, 200, 109, 270, 169, 128,
       119, 175, 111, 193, 173, 189, 232,  64, 144,  53, 138, 124, 374,
       170, 138, 199, 138, 120, 246, 208, 137, 261, 127, 161, 212, 203,
       206, 187, 274, 201, 201, 174, 176, 185, 223, 109, 158, 203, 174,
       205, 152, 129, 206, 113, 127, 171, 164, 134,  95, 109,  67, 122,
       127, 333, 160, 311, 136, 207, 119, 222, 107], dtype=int64)

# Assignment

### Confusion Matrix 

In [38]:
print(confusion_matrix(ytest,p))

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


### Specificity and Sensitivity

In [36]:
c = confusion_matrix(ytest,p)
print('Specificity: ', c[1,1]/(c[1,0]+c[1,1]))
print('Sensitivity: ', c[0,0]/(c[0,0]+c[0,1]))

Specificity:  nan
Sensitivity:  nan
<ipython-input-36-6128350372b0>:2: RuntimeWarning: invalid value encountered in longlong_scalars
  print('Specificity: ', c[1,1]/(c[1,0]+c[1,1]))
<ipython-input-36-6128350372b0>:3: RuntimeWarning: invalid value encountered in longlong_scalars
  print('Sensitivity: ', c[0,0]/(c[0,0]+c[0,1]))


### Accuracy

In [60]:
c = confusion_matrix(ytest,p)
print('Accuracy: {:.5%}'.format((c[0,0]+c[1,1])/sum(sum(c))))

Accuracy: 90.90909%
