# Allen Ben Philipose - 18BIS0043
#### Mock Lab FAT, L53+L54
#### ECE3502 - IoT Domain Analyst
#### Submitted to: Prof. Pradheep T

# Aim

In the given dataset, use random forest and predict the online shopping website for 
- Naypyitaw,Male,134,8.4 (Reg.No: 18BEC0402)

# Code and Result

## Import Libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
from sklearn import preprocessing
from sklearn.metrics import accuracy_score, log_loss, confusion_matrix, f1_score 
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.model_selection import StratifiedKFold, GridSearchCV, KFold 
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import classification_report

In [3]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

In [4]:
import warnings
warnings.filterwarnings('ignore')

## Dataset

In [5]:
allen = pd.read_csv("Dataset.csv")

In [8]:
allen.head()

Invoice ID Branch       City Customer type  Gender  \
0  750-67-8428      A     Yangon        Member  Female   
1  226-31-3081      C  Naypyitaw        Normal  Female   
2  631-41-3108      A     Yangon        Normal    Male   
3  123-19-1176      A     Yangon        Member    Male   
4  373-73-7910      A     Yangon        Normal    Male   

             Product line  Unit price  Quantity   Tax 5%     Total       Date  \
0       Health and beauty       74.69         7  26.1415  548.9715   1/5/2019   
1  Electronic accessories       15.28         5   3.8200   80.2200   3/8/2019   
2      Home and lifestyle       46.33         7  16.2155  340.5255   3/3/2019   
3       Health and beauty       58.22         8  23.2880  489.0480  1/27/2019   
4       Sports and travel       86.31         7  30.2085  634.3785   2/8/2019   

    Time      Payment    cogs  gross margin percentage  gross income  Rating  
0  13:08      Ewallet  522.83                 4.761905       26.1415     9.1  
1  10:29         Cash   76.40                 4.761905        3.8200     9.6  
2  13:23  Credit card  324.31                 4.761905       16.2155     7.4  
3  20:33      Ewallet  465.76                 4.761905       23.2880     8.4  
4  10:37      Ewallet  604.17                 4.761905       30.2085     5.3

In [9]:
allen.drop('Invoice ID',axis=1, inplace=True)
allen.drop('Branch',axis=1, inplace=True)
allen.drop('Customer type',axis=1, inplace=True)
allen.drop('Quantity',axis=1, inplace=True)
allen.drop('Tax 5%',axis=1, inplace=True)
allen.drop('Total',axis=1, inplace=True)
allen.drop('Time',axis=1, inplace=True)
allen.drop('Date',axis=1, inplace=True)
allen.drop('cogs',axis=1, inplace=True)
allen.drop('gross margin percentage',axis=1, inplace=True)
allen.drop('gross income',axis=1, inplace=True)
allen.drop('Payment',axis=1, inplace=True)

In [10]:
allen.head()

City  Gender            Product line  Unit price  Rating
0     Yangon  Female       Health and beauty       74.69     9.1
1  Naypyitaw  Female  Electronic accessories       15.28     9.6
2     Yangon    Male      Home and lifestyle       46.33     7.4
3     Yangon    Male       Health and beauty       58.22     8.4
4     Yangon    Male       Sports and travel       86.31     5.3

## Label Encoding

In [11]:
l1 = preprocessing.LabelEncoder()
f1 = l1.fit_transform(allen['Gender']) 
f1 = pd.DataFrame(data=f1, columns=['Gender'])
allen['Gender'] = f1['Gender']

In [12]:
print(list(l1.inverse_transform([0,1])))

['Female', 'Male']


In [13]:
l2 = preprocessing.LabelEncoder()
f2 = l2.fit_transform(allen['City']) 
f2 = pd.DataFrame(data=f2, columns=['City'])
allen['City'] = f2['City']

In [15]:
print(list(l2.inverse_transform([0,1,2])))

['Mandalay', 'Naypyitaw', 'Yangon']


In [18]:
l3 = preprocessing.LabelEncoder()
f3 = l3.fit_transform(allen['Product line'])
f3 = pd.DataFrame(data=f3, columns=['Product line'])
allen['Product line'] = f3['Product line']

In [19]:
print(list(l3.inverse_transform([0,1,2,3,4,5])))

['Electronic accessories', 'Fashion accessories', 'Food and beverages', 'Health and beauty', 'Home and lifestyle', 'Sports and travel']


In [21]:
allen.head()

City  Gender  Product line  Unit price  Rating
0     2       0             3       74.69     9.1
1     1       0             0       15.28     9.6
2     2       1             4       46.33     7.4
3     2       1             3       58.22     8.4
4     2       1             5       86.31     5.3

## MinMaxScaler

In [22]:
ms = MinMaxScaler()
columns = ['Unit price']
allen[columns] = ms.fit_transform(allen[columns])

In [23]:
allen.head()

City  Gender  Product line  Unit price  Rating
0     2       0             3    0.718847     9.1
1     1       0             0    0.057855     9.6
2     2       1             4    0.403316     7.4
3     2       1             3    0.535603     8.4
4     2       1             5    0.848131     5.3

## Train-test-split

In [24]:
x = allen.drop(['Product line'],axis=1)

In [25]:
y = allen['Product line']

In [26]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.2,random_state=21)

## Model

In [46]:
model0 = RandomForestClassifier()
model0.fit(xtrain,ytrain)
p0 = model0.predict(xtest)

## Prediction (18BIS0043)

In [47]:
allen2 = pd.DataFrame(columns=['City','Gender','Unit price','Rating','Product line'])

In [48]:
init = {"City": 1,
        "Gender": 1,
        "Unit price": 134,
        "Rating": 8.4,
       }
allen2 = allen2.append(init, ignore_index=True)

In [49]:
pred = model0.predict(allen2.drop(['Product line'],axis=1))
allen2['Product line']=pred

In [50]:
allen2.head()

City  Gender  Unit price  Rating  Product line
0   1.0     1.0       134.0     8.4             3

In [51]:
print(list(l3.inverse_transform([allen2['Product line']])))

['Health and beauty']


In [52]:
print(classification_report(ytest.values.ravel(),p0,target_names=['0','1','2','3','4','5']))

              precision    recall  f1-score   support

           0       0.11      0.10      0.11        39
           1       0.10      0.11      0.10        37
           2       0.19      0.15      0.16        48
           3       0.10      0.08      0.09        25
           4       0.07      0.07      0.07        27
           5       0.21      0.33      0.26        24

    accuracy                           0.14       200
   macro avg       0.13      0.14      0.13       200
weighted avg       0.13      0.14      0.13       200



# Viva

Which ML algorithm is the most effective for this application given the same dataset. Justify your choice of ML algorithm.

#### Random Forest

In [53]:
model1 = RandomForestClassifier()
model1.fit(xtrain,ytrain)
p1 = model1.predict(xtest)

In [54]:
print(confusion_matrix(ytest,p1))

[[ 3  7 12  9  6  2]
 [ 9  5  6  4  4  9]
 [12 10  8  3 10  5]
 [ 4  9  4  1  3  4]
 [ 6  7  6  3  1  4]
 [ 2  5  2  3  2 10]]


In [56]:
print(classification_report(ytest.values.ravel(),p1,target_names=['0','1','2','3','4','5']))

              precision    recall  f1-score   support

           0       0.08      0.08      0.08        39
           1       0.12      0.14      0.12        37
           2       0.21      0.17      0.19        48
           3       0.04      0.04      0.04        25
           4       0.04      0.04      0.04        27
           5       0.29      0.42      0.34        24

    accuracy                           0.14       200
   macro avg       0.13      0.15      0.14       200
weighted avg       0.13      0.14      0.14       200



#### Decision Tree

In [57]:
model2 = DecisionTreeClassifier()
model2.fit(xtrain,ytrain)
p2 = model2.predict(xtest)

In [58]:
print(confusion_matrix(ytest,p2))

[[ 5  6 10  7  6  5]
 [10  3  5  5  5  9]
 [ 9 11  8  3 11  6]
 [ 6  4  4  1  6  4]
 [ 7  6  4  1  3  6]
 [ 2  6  1  2  1 12]]


In [59]:
print(classification_report(ytest.values.ravel(),p2,target_names=['0','1','2','3','4','5']))

              precision    recall  f1-score   support

           0       0.13      0.13      0.13        39
           1       0.08      0.08      0.08        37
           2       0.25      0.17      0.20        48
           3       0.05      0.04      0.05        25
           4       0.09      0.11      0.10        27
           5       0.29      0.50      0.36        24

    accuracy                           0.16       200
   macro avg       0.15      0.17      0.15       200
weighted avg       0.15      0.16      0.15       200



#### Naive Bayes

In [60]:
model3 = GaussianNB()
model3.fit(xtrain,ytrain)
p3 = model3.predict(xtest)

In [61]:
print(confusion_matrix(ytest,p3))

[[ 4  8  1  9 12  5]
 [ 2  7  0 15  7  6]
 [ 8 12  1  9  9  9]
 [ 3  8  1  8  4  1]
 [ 5  1  1 11  4  5]
 [ 3  3  4  5  5  4]]


In [62]:
print(classification_report(ytest.values.ravel(),p3,target_names=['0','1','2','3','4','5']))

              precision    recall  f1-score   support

           0       0.16      0.10      0.12        39
           1       0.18      0.19      0.18        37
           2       0.12      0.02      0.04        48
           3       0.14      0.32      0.20        25
           4       0.10      0.15      0.12        27
           5       0.13      0.17      0.15        24

    accuracy                           0.14       200
   macro avg       0.14      0.16      0.13       200
weighted avg       0.14      0.14      0.13       200



#### K-Nearest Neighbour

In [63]:
model4 = KNeighborsClassifier()
model4.fit(xtrain,ytrain)
p4 = model4.predict(xtest)

In [64]:
print(confusion_matrix(ytest,p4))

[[12  7 10  2  3  5]
 [12  5  5  5  7  3]
 [19  8  8  2  6  5]
 [ 6  6  5  5  1  2]
 [ 9  5  4  4  1  4]
 [10  2  3  4  2  3]]


In [65]:
print(classification_report(ytest.values.ravel(),p4,target_names=['0','1','2','3','4','5']))

              precision    recall  f1-score   support

           0       0.18      0.31      0.22        39
           1       0.15      0.14      0.14        37
           2       0.23      0.17      0.19        48
           3       0.23      0.20      0.21        25
           4       0.05      0.04      0.04        27
           5       0.14      0.12      0.13        24

    accuracy                           0.17       200
   macro avg       0.16      0.16      0.16       200
weighted avg       0.17      0.17      0.16       200



#### Logistic Regression

In [66]:
model5 = LogisticRegression()
model5.fit(xtrain,ytrain)
p5 = model5.predict(xtest)

In [67]:
print(confusion_matrix(ytest,p5))

[[ 4  6  1  8 13  7]
 [ 1  6  2 14  9  5]
 [10 11  3  7  8  9]
 [ 3  7  1  8  5  1]
 [ 5  2  2  9  5  4]
 [ 3  3  4  2  7  5]]


In [68]:
print(classification_report(ytest.values.ravel(),p5,target_names=['0','1','2','3','4','5']))

              precision    recall  f1-score   support

           0       0.15      0.10      0.12        39
           1       0.17      0.16      0.17        37
           2       0.23      0.06      0.10        48
           3       0.17      0.32      0.22        25
           4       0.11      0.19      0.14        27
           5       0.16      0.21      0.18        24

    accuracy                           0.15       200
   macro avg       0.17      0.17      0.15       200
weighted avg       0.17      0.15      0.15       200



## K-Fold Analysis

In [69]:
kfold = StratifiedKFold(n_splits=6, shuffle=True, random_state=21)

#### Random Forest

In [70]:
acc = np.mean(cross_val_score(model1, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [71]:
allen11 = pd.DataFrame({'Model':'Random Forest',
                      'Accuracy':[acc]})

#### Decision Tree

In [72]:
acc = np.mean(cross_val_score(model2, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [73]:
allen12 = pd.DataFrame({'Model':'Decision Tree',
                      'Accuracy':[acc]})

#### Naive Bayes

In [74]:
acc = np.mean(cross_val_score(model3, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [75]:
allen13 = pd.DataFrame({'Model':'Naive Bayes',
                      'Accuracy':[acc]})

#### K-Nearest Neighbour

In [76]:
acc = np.mean(cross_val_score(model4, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [77]:
allen14 = pd.DataFrame({'Model':'K-Nearest Neighbour',
                      'Accuracy':[acc]})

#### Logistic Regression

In [78]:
acc = np.mean(cross_val_score(model5, xtrain, ytrain, scoring='accuracy', cv=kfold))

In [79]:
allen15 = pd.DataFrame({'Model':'Logistic Regression',
                      'Accuracy':[acc]})

#### Concat

In [80]:
al = pd.concat([allen11,allen12,allen13,allen14,allen15],axis=0).reset_index()
al = al.drop('index',axis=1)
al

Model  Accuracy
0        Random Forest  0.177487
1        Decision Tree  0.156268
2          Naive Bayes  0.158690
3  K-Nearest Neighbour  0.176318
4  Logistic Regression  0.164946

Using the K-Fold Analysis, a method for comparison, we can compare the algorithms based on the accuracies offered by them. Here, the highest accuracy offered is by Decision Tree ML algorithm, closely followed by Random Forest ML algorithm,for the given scenario and dataset.